# -*- coding: utf-8 -*-
"""Placement And Training Management System.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rHyTELBSMdtn9AtSsY8eQTzgZCtsJPA-

# Placement And Training Management System

# Database Creation
"""

import sqlite3

my_conn = sqlite3.connect("TPOMSSoftware.db")
print("Created Database Successfully .")

"""#Login

"""

import getpass

def login(choice) :
  if(choice is ( 1 or 2 )):
    print("\n----------------------Login Account As , Please Identify Yourself As---------------------\n")
    print("------------------------------------------------------------------------------------------")
    print("| 1 | User                                                                               |")
    print("------------------------------------------------------------------------------------------")
    print("| 2 | Company                                                                            |")
    print("------------------------------------------------------------------------------------------")
    print("| 3 | Service Provider                                                                   |")
    print("------------------------------------------------------------------------------------------")
    print("| 4 | Developer                                                                          |")
    print("------------------------------------------------------------------------------------------\n\n")

    j = int(input("Enter The Number Of Your choice   :- "))
    let_login = j

    if(j == 1):
      email = input("Enter Your Personal Email Id :- ")
      print("Enter Your Password :- ",end = '')
      password = getpass.getpass()

      
      #Create Table
      my_conn.execute('''
      CREATE TABLE IF NOT EXISTS login_user
      (
      email text , 
      password text 
      );''')
      my_conn.commit()
      print("Login Account User Created Successfully . ")

      #Insert Data
      my_conn.execute("insert into login_user values(?,?)",(email , password))

      Placement_Or_Training(let_login)
  
    elif(j == 2):
      email = input("Enter Your Recruiter's / Company's Email Id :- ")
      print("Enter Your Password :- ",end = '')
      password = getpass.getpass()

      #Create Table
      my_conn.execute('''
      CREATE TABLE IF NOT EXISTS login_recruiter
      (
      email text , 
      password text 
      );''')
      my_conn.commit()
      print("Login Account Recruiter Created Successfully . ")

      #Insert Data
      my_conn.execute("insert into login_recruiter values(?,?)",(email , password))

      Placement(let_login)


    elif(j == 3):
      email = input("Enter Your Service Provider Email Id :- ")
      print("Enter Your Password :- ",end = '')
      password = getpass.getpass()

      #Create Table
      my_conn.execute('''
      CREATE TABLE IF NOT EXISTS login_service_provider
      (
      email text , 
      password text 
      );''')
      my_conn.commit()
      print("Login Account Service Provider Created Successfully . ")

      #Insert Data
      my_conn.execute("insert into login_service_provider values(?,?)",(email , password))

      Training(let_login)

"""#Create Account ."""

def create_account(choice) :

  if(choice is 2):
    print("----------------------Create Account As , Please Identify Yourself As---------------------")
    print("------------------------------------------------------------------------------------------")
    print("| 1 | User                                                                               |")
    print("------------------------------------------------------------------------------------------")
    print("| 2 | Company                                                                            |")
    print("------------------------------------------------------------------------------------------")
    print("| 3 | Service Provider                                                                   |")
    print("------------------------------------------------------------------------------------------")
    #print("Note / P.S :- 4 -- > If Developer Or Software Handler , Then No Need To Create Account , As Account Is Already Developed By Company , So Only Login For It , With Your Identity Card ID ( Unique ) And Put Password As Your Personal Computer Password .")

    j = int(input("Enter The Number Of Your choice   :- "))

    let_create_account = j

    if(j == 1):
      Name = input("Enter Your Name :- ")
      FatherName = input("Enter Your Father's Name :- ")
      MotherName = input("Enter Your Mother's Name :- ")
      Phone = int(input("Enter Your Personal Mobile / Phone Number :- "))
      Email = input("Enter Your Personal Email Id :- ")
      CollegeID = input("Enter Your College ID :- ")
      CGPA = float(input("Enter Your CGPA Aggregate Till Latest Result :- "))
      Linkedln = input("Enter Your Linkedln ID / Link / If not then write 'No':- ")
      Password = input("Enter Your Password :- ")

      #Create Table
      my_conn.execute('''
      CREATE TABLE IF NOT EXISTS account_user
      (
      name text ,
      fname text,
      mname text ,
      phone number, 
      email text ,
      collegeid text Primary Key , 
      CGPA number,
      linkedln text ,
      password text UNIQUE 
      );''')
      my_conn.commit()
      print("Create Account Created Successfully . ")
  
      #Insert Data
      my_conn.execute("insert into account_user values(?,?,?,?,?,?,?,?,?)",(Name,FatherName,MotherName,Phone,Email,CollegeID,CGPA,Linkedln,Password))
  
      Placement_Or_Training(let_create_account)

    elif(j == 2):
      Name = input("Enter Your Company Name :- ")
      Address = input("Enter Your Address :- ")
      City = input("Enter Your City :- ")
      State = input("Enter Your State :- ")
      Country = input("Enter Your Country :- ")
      Email = input("Enter Your Personal Email Id :- ")
      Linkedln = input("Enter Your Linkedln ID / Link :- ")
      Website = input("Enter Your Personal Website :- ")
      Password = input("Enter Your Personal Password ( Don't Disclose It To Anyone .................)")
      #Create Table
      my_conn.execute('''
      CREATE TABLE IF NOT EXISTS account_recruiter
      (
      name text ,
      address text ,
      city text ,
      state text , 
      country text ,
      email text Primary Key , 
      linkedln text ,
      website text ,
      password text UNIQUE 
      );''')
      my_conn.commit()
      print("Create Account Recruiter / Company Created Successfully . ")
  
      #Insert Data
      my_conn.execute("insert into account_recruiter values(?,?,?,?,?,?,?,?,?)",(Name , Address , City , State , Country , Email , Linkedln , Website , Password))

      Placement(let_create_account)

    elif(j == 3):
      Name = input("Enter Your Company Name :- ")
      Address = input("Enter Your Address :- ")
      City = input("Enter Your City :- ")
      State = input("Enter Your State :- ")
      Country = input("Enter Your Country :- ")
      Email = input("Enter Your Personal Email Id :- ")
      Linkedln = input("Enter Your Linkedln ID / Link :- ")
      Website = input("Enter Your Personal Website :- ")
      Password = input("Enter Your Personal Password ( Don't Disclose It To Anyone .................)")
      
      #Create Table
      my_conn.execute('''
      CREATE TABLE IF NOT EXISTS account_service_provider
      (
      name text ,
      address text ,
      city text ,
      state text , 
      country text ,
      email text Primary Key , 
      linkedln text ,
      website text ,
      password text UNIQUE 
      );''')
      my_conn.commit()
      print("Create Account Service Provider Created Successfully . ")

      #Insert Data
      my_conn.execute("insert into account_service_provider values(?,?,?,?,?,?,?,?,?)",(Name , Address , City , State , Country , Email , Linkedln , Website , Password))

      Training(let_create_account)

"""#Placement Or Training ."""

def Placement_Or_Training(ll):
  choice = 1 
  while ( choice == 1 or choice == 2):
    print("--------- Placement Or Training ---------")
    print("-----------------------------------------")
    print("| 1 | Placement                         |")
    print("-----------------------------------------")
    print("| 2 | Training                          |")
    print("-----------------------------------------")
    print("| 3 | Logout                            |")
    print("-----------------------------------------")
    choice  = int(input("Enter The Number Of Your choice   :- "))
    if(choice  == 1) :
      Placement(ll)
    elif(choice  == 2) :
      Training(ll)

"""# Placement ."""

def Placement(pp) :
  a = pp
  while a is 2 :
    CName = input("Enter Your Company Name :- ")
    JPoisition = input("Enter The Job Position Company Provides :- ")
    JRequirements = input("Enter The Job Profile Requirements Company Is Asking :- ")
    JSalary = float(input("Enter The Average Salary Or CTC Offered By Company :- "))
    JStartDate = input("Enter Starting Date For Enrollement Process :- ")
    JEndDate = input("Enter End Date For Enrollement Process :- ")
    JFormFill = input("Enter The Website Where Online Enrollement Form Need To Fill / If Offline Then Company Address Where Enrollement Form Needs To Fill :-  ")
    JResources = input("Enter Resources For Prepration ( Website Or PDF Link ) / if not then write NA :- ")
    JMoreInformation = input("Enter The Number Or Website For More Information Or Resolution Of Query :- ")

    #Create Table
    my_conn.execute('''
    CREATE TABLE IF NOT EXISTS placement
    (
    name text ,
    position text ,
    requirements text ,
    salary number , 
    sdate text , 
    edate text ,
    formfill text , 
    resources text ,
    moreinformation text 
    );''')
    my_conn.commit()
    print("Placement Table Created Successfully . ")
  
    #Insert Data
    my_conn.execute("insert into placement values(?,?,?,?,?,?,?,?,?)",(CName,JPoisition,JRequirements,JSalary,JStartDate, JEndDate,JFormFill,JResources,JMoreInformation))

    if pp is not 3 :
      #Represent Data Placement ( Recruiter )
      r_set=my_conn.execute('''SELECT * from placement''');
      for row in r_set:
        print(row)

    a = int(input("Enter 3 for Logout or 2 to continue ."))

"""# Training ."""

def Training(tt) :
  b = tt
  while b is 3 :
    TName = input("Enter Your Company Or Training Institute Name :- ")
    TCourse = input("Enter The Course Company Or Training Institute Provides :- ")
    TCost = float(input("Enter The Average Cost Or Total / Complete Fees Asked By Company Or Training Institute For Course / Training Offered  :- "))
    TStartDate = input("Enter Starting Date For Enrollement Process :- ")
    TEndDate = input("Enter End Date For Enrollement Process :- ")
    TFormFill = input("Enter The Website Where Online Enrollement Form Need To Fill / If Offline Then Company Or Training Institute Address Where Enrollement Form Needs To Fill :-  ")
    TResources = input("Enter Sample Resources ( Website Or PDF Link ) / if not then write NA :- ")
    TCertifications = input("Enter If Certificate Provide --> Yes or yes or y or YA and If Not Provided Certificate Then --> No or no or n or NA")
    TMoreInformation = input("Enter The Number Or Website For More Information Or Resolution Of Query :- ")

    #Create Table
    my_conn.execute('''
    CREATE TABLE IF NOT EXISTS training
    (
    name text ,
    course text ,
    cost number , 
    sdate text , 
    edate text ,
    formfill text , 
    resources text ,
    certifications text ,
    moreinformation text 
    );''')
    my_conn.commit()
    print("Training Table Created Successfully . ")
  
    #Insert Data
    my_conn.execute("insert into training values(?,?,?,?,?,?,?,?,?)",(TName,TCourse,TCost,TStartDate, TEndDate,TFormFill,TResources,TCertifications,TMoreInformation))

    if tt is not 2 :
      #Represent Data Training ( Service Provider ) .
      r_set=my_conn.execute('''SELECT * from training''');
      for row in r_set:
        print(row)

    b = int(input("Input 4 for Logout and 3 for Continue ."))

"""#TPO"""

import webbrowser

print("-----------------Welcome To Placement And Training Management System Software-------------")
print("------------------------------------------------------------------------------------------")
print("| 1 | Login                                                                              |")
print("------------------------------------------------------------------------------------------")
print("| 2 | Create Account                                                                      ")
print("------------------------------------------------------------------------------------------")
print("| 3 | Developer                                                                           ")
print("------------------------------------------------------------------------------------------")
choice = int(input("Enter The Number Of Your choice   :- "))
if(choice == 1):
  login(choice)
elif(choice == 2):
  create_account(choice)
elif(choice == 3):
  webbrowser.open('https://colab.research.google.com/drive/1WyVy55Ry0bGjbYQptVmq4DxIEs0bRmn-#scrollTo=AY3VymCrDGZM')
  #Open Web Browser When Using ".py" or "executable python file " in Python Programming Language In Google Colab Using Webbrowser Library or Importing It To Open An URL in New Tab .

print("Logout Successfully ..................................................................................................")
print("Please Visit The Website Again .\nThank You .\nBy . ")